blacklist usb-storage
blacklist firewire-core
blacklist thunderbolt
blacklist bluetooth
blacklist btusb
install usb-storage /bin/false
install firewire-core /bin/false
install thunderbolt /bin/false
install bluetooth /bin/false
