#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif lo accept
        ct state established,related accept
        ip protocol icmp icmp type echo-request limit rate 1/second accept
        tcp dport 2222 ct state new limit rate 3/minute accept
        tcp flags & (syn|ack) == syn jump syn_flood
        log prefix "nftables DROP: " flags all counter drop
    }
    chain syn_flood {
        limit rate 10/second burst 20 packets return
        drop
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
